openapi: 3.0.0
info:
  contact:
    email: support@sophos.com
    name: Sophos-public-api-handler
    url: https://cloud.sophos.com/
  description: Swagger Specifications for public APIs
  license:
    name: Sophos Central License
    url: https://www.sophos.com/en-us/legal/sophos-professional-services.aspx
  termsOfService: https://www.sophos.com/en-us/legal/sophos-end-user-license-agreement.aspx
  title: Sophos Public API
  version: beta
servers:
- url: https://api1.central.sophos.com/gateway
tags:
- description: Retrieve events for a given customer
  name: event-controller-v-1-impl
- description: Retrieve alerts for a given customer
  name: alert-controller-v-1-impl
- description: API to provide data required for migration to cloud
  name: sec-migration-controller-v-1-impl
paths:
  /migration-tool/v1/deployment/agent/locations:
    get:
      operationId: getInstallerInfoUsingGET_1
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallerInfoResponse'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get the installer information.
      tags:
      - sec-migration-controller-v-1-impl
  /migration-tool/v1/download/hashes:
    get:
      operationId: hashesUsingGET_1
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HashesResponse'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get SHA1 hashes for all available installer templates.
      tags:
      - sec-migration-controller-v-1-impl
  /migration-tool/v1/endpoints:
    get:
      operationId: endpointsUsingGET_1
      parameters:
      - description: The timestamp to start searching from
        explode: true
        in: query
        name: since
        required: false
        schema:
          type: string
        style: form
      - description: The paging offset
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointsResponse'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get endpoints for customer based on the parameters provided
      tags:
      - sec-migration-controller-v-1-impl
  /migration-tool/v1/features/current:
    get:
      operationId: getCustomerFeaturesUsingGET_1
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerFeaturesResponse'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get current features for a customer
      tags:
      - sec-migration-controller-v-1-impl
  /migration-tool/v1/licenses/current:
    get:
      operationId: getCurrentLicensesUsingGET_1
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentLicensesResponse'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get current licenses for customer
      tags:
      - sec-migration-controller-v-1-impl
  /siem/v1/alerts:
    get:
      description: 'Note: Alerts are retrieved for timestamps within last 24 hours'
      operationId: getAlertsUsingGET_1
      parameters:
      - description: The maximum number of items to return, default is 200, max is
          1000
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 200
          format: int32
          maximum: 1000
          minimum: 200
          type: integer
        style: form
      - description: The starting date from which alerts will be retrieved defined
          as Unix timestamp in UTC. Ignored if cursor is set. Must be within last
          24 hours.
        explode: true
        in: query
        name: from_date
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: Identifier for next item in the list, this value is available
          in response as next_cursor. Response will default to last 24 hours if cursor
          is not within last 24 hours.
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertAggregate'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get alerts for customer based on the parameters provided
      tags:
      - alert-controller-v-1-impl
  /siem/v1/events:
    get:
      description: 'Note: Events are retrieved for timestamps within last 24 hours'
      operationId: getEventsUsingGET_1
      parameters:
      - description: The maximum number of items to return, default is 200, max is
          1000
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 200
          format: int32
          maximum: 1000
          minimum: 200
          type: integer
        style: form
      - description: Identifier for next item in the list, this value is available
          in response as next_cursor. Response will default to last 24 hours if cursor
          is not within last 24 hours.
        explode: true
        in: query
        name: cursor
        required: false
        schema:
          type: string
        style: form
      - description: The starting date from which alerts will be retrieved defined
          as Unix timestamp in UTC.Ignored if cursor is set. Must be within last 24
          hours
        explode: true
        in: query
        name: from_date
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: The String of list of types of events to be excluded
        explode: true
        in: query
        name: exclude_types
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Authorization
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: X-Timestamp
        required: false
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventAggregate'
          description: OK
        400:
          description: Bad Request
        401:
          description: customer not authorized to make api call
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal Server Error
      security:
      - api_key: []
      summary: Get events for customer based on the parameters provided
      tags:
      - event-controller-v-1-impl
components:
  schemas:
    EndpointsResponse:
      description: Sophos Central Endpoints Model
      example:
        total: 6
        filtered: 0
        next_key: next_key
        items:
        - adSyncInfo:
            name: name
            dn: dn
            external_id: external_id
            from_ad_sync: true
          device_encryption_status_unmanaged: true
          feature_codes:
          - feature_codes
          - feature_codes
          last_user_id: last_user_id
          awsInfo:
            key: awsInfo
          last_activity: last_activity
          last_user: last_user
          group_full_name: group_full_name
          health_status: 1
          id: id
          beta: true
          java_id: java_id
          license_codes:
          - license_codes
          - license_codes
          info: '{}'
          heartbeat_utm_name: heartbeat_utm_name
          early_access_program: early_access_program
          decloned_from: decloned_from
          registered_at: registered_at
          group_name: group_name
          machine_id: machine_id
          tamper_protection:
            globally_enabled: true
            password: password
            previous_passwords:
            - password: password
              invalidated:
                dayOfYear: 7
                equalNow: true
                year: 5
                weekyear: 4
                chronology:
                  zone:
                    fixed: true
                    id: id
                weekOfWeekyear: 1
                secondOfMinute: 7
                millisOfDay: 4
                monthOfYear: 1
                beforeNow: true
                dayOfWeek: 2
                minuteOfDay: 1
                dayOfMonth: 5
                era: 9
                zone:
                  fixed: true
                  id: id
                yearOfCentury: 9
                centuryOfEra: 5
                hourOfDay: 3
                secondOfDay: 6
                millis: 2
                yearOfEra: 9
                minuteOfHour: 1
                afterNow: true
                millisOfSecond: 7
            - password: password
              invalidated:
                dayOfYear: 7
                equalNow: true
                year: 5
                weekyear: 4
                chronology:
                  zone:
                    fixed: true
                    id: id
                weekOfWeekyear: 1
                secondOfMinute: 7
                millisOfDay: 4
                monthOfYear: 1
                beforeNow: true
                dayOfWeek: 2
                minuteOfDay: 1
                dayOfMonth: 5
                era: 9
                zone:
                  fixed: true
                  id: id
                yearOfCentury: 9
                centuryOfEra: 5
                hourOfDay: 3
                secondOfDay: 6
                millis: 2
                yearOfEra: 9
                minuteOfHour: 1
                afterNow: true
                millisOfSecond: 7
            enabled: true
          transport: transport
          azureInfo:
            key: azureInfo
          deleted_at: deleted_at
          alert_status: 6
          is_adsync_group: true
          cloned: true
          endpoint_type: endpoint_type
          group_id: group_id
          name: name
          assignedProducts:
          - assignedProducts
          - assignedProducts
          is_caching_proxy: true
          status: '{}'
        - adSyncInfo:
            name: name
            dn: dn
            external_id: external_id
            from_ad_sync: true
          device_encryption_status_unmanaged: true
          feature_codes:
          - feature_codes
          - feature_codes
          last_user_id: last_user_id
          awsInfo:
            key: awsInfo
          last_activity: last_activity
          last_user: last_user
          group_full_name: group_full_name
          health_status: 1
          id: id
          beta: true
          java_id: java_id
          license_codes:
          - license_codes
          - license_codes
          info: '{}'
          heartbeat_utm_name: heartbeat_utm_name
          early_access_program: early_access_program
          decloned_from: decloned_from
          registered_at: registered_at
          group_name: group_name
          machine_id: machine_id
          tamper_protection:
            globally_enabled: true
            password: password
            previous_passwords:
            - password: password
              invalidated:
                dayOfYear: 7
                equalNow: true
                year: 5
                weekyear: 4
                chronology:
                  zone:
                    fixed: true
                    id: id
                weekOfWeekyear: 1
                secondOfMinute: 7
                millisOfDay: 4
                monthOfYear: 1
                beforeNow: true
                dayOfWeek: 2
                minuteOfDay: 1
                dayOfMonth: 5
                era: 9
                zone:
                  fixed: true
                  id: id
                yearOfCentury: 9
                centuryOfEra: 5
                hourOfDay: 3
                secondOfDay: 6
                millis: 2
                yearOfEra: 9
                minuteOfHour: 1
                afterNow: true
                millisOfSecond: 7
            - password: password
              invalidated:
                dayOfYear: 7
                equalNow: true
                year: 5
                weekyear: 4
                chronology:
                  zone:
                    fixed: true
                    id: id
                weekOfWeekyear: 1
                secondOfMinute: 7
                millisOfDay: 4
                monthOfYear: 1
                beforeNow: true
                dayOfWeek: 2
                minuteOfDay: 1
                dayOfMonth: 5
                era: 9
                zone:
                  fixed: true
                  id: id
                yearOfCentury: 9
                centuryOfEra: 5
                hourOfDay: 3
                secondOfDay: 6
                millis: 2
                yearOfEra: 9
                minuteOfHour: 1
                afterNow: true
                millisOfSecond: 7
            enabled: true
          transport: transport
          azureInfo:
            key: azureInfo
          deleted_at: deleted_at
          alert_status: 6
          is_adsync_group: true
          cloned: true
          endpoint_type: endpoint_type
          group_id: group_id
          name: name
          assignedProducts:
          - assignedProducts
          - assignedProducts
          is_caching_proxy: true
          status: '{}'
      properties:
        filtered:
          format: int32
          type: integer
        items:
          items:
            $ref: '#/components/schemas/EndpointEntity'
          type: array
        next_key:
          type: string
        total:
          format: int32
          type: integer
      type: object
    InstallerHashesEntity:
      type: object
    AlertAggregate:
      description: Sophos Central Alert Model
      example:
        next_cursor: next_cursor
        has_more: true
        items:
        - severity: LOW
          data:
            key: '{}'
          created_at: created_at
          description: description
          source: source
          type: type
          when: when
          threat_cleanable: true
          event_service_event_id: event_service_event_id
          location: location
          id: id
          threat: threat
          customer_id: customer_id
          info:
            key: '{}'
        - severity: LOW
          data:
            key: '{}'
          created_at: created_at
          description: description
          source: source
          type: type
          when: when
          threat_cleanable: true
          event_service_event_id: event_service_event_id
          location: location
          id: id
          threat: threat
          customer_id: customer_id
          info:
            key: '{}'
      properties:
        has_more:
          type: boolean
        items:
          items:
            $ref: '#/components/schemas/AlertEntity'
          type: array
        next_cursor:
          description: Value of the next cursor. This will be used to make next call
            of api
          type: string
      type: object
    EndpointCoreEventCertificate:
      example:
        thumbprint: thumbprint
        signer: signer
      properties:
        signer:
          type: string
        thumbprint:
          type: string
      type: object
    DateTime:
      example:
        dayOfYear: 7
        equalNow: true
        year: 5
        weekyear: 4
        chronology:
          zone:
            fixed: true
            id: id
        weekOfWeekyear: 1
        secondOfMinute: 7
        millisOfDay: 4
        monthOfYear: 1
        beforeNow: true
        dayOfWeek: 2
        minuteOfDay: 1
        dayOfMonth: 5
        era: 9
        zone:
          fixed: true
          id: id
        yearOfCentury: 9
        centuryOfEra: 5
        hourOfDay: 3
        secondOfDay: 6
        millis: 2
        yearOfEra: 9
        minuteOfHour: 1
        afterNow: true
        millisOfSecond: 7
      properties:
        afterNow:
          type: boolean
        beforeNow:
          type: boolean
        centuryOfEra:
          format: int32
          type: integer
        chronology:
          $ref: '#/components/schemas/Chronology'
        dayOfMonth:
          format: int32
          type: integer
        dayOfWeek:
          format: int32
          type: integer
        dayOfYear:
          format: int32
          type: integer
        equalNow:
          type: boolean
        era:
          format: int32
          type: integer
        hourOfDay:
          format: int32
          type: integer
        millis:
          format: int64
          type: integer
        millisOfDay:
          format: int32
          type: integer
        millisOfSecond:
          format: int32
          type: integer
        minuteOfDay:
          format: int32
          type: integer
        minuteOfHour:
          format: int32
          type: integer
        monthOfYear:
          format: int32
          type: integer
        secondOfDay:
          format: int32
          type: integer
        secondOfMinute:
          format: int32
          type: integer
        weekOfWeekyear:
          format: int32
          type: integer
        weekyear:
          format: int32
          type: integer
        year:
          format: int32
          type: integer
        yearOfCentury:
          format: int32
          type: integer
        yearOfEra:
          format: int32
          type: integer
        zone:
          $ref: '#/components/schemas/DateTimeZone'
      type: object
    EventDetailProperty:
      example:
        property: property
        type: CORE_EVENT_REQUEST_ID
      properties:
        property:
          type: string
        type:
          enum:
          - CORE_EVENT_REQUEST_ID
          - CORE_EVENT_RESPONSE_STATUS
          - HMPA_EVENT_REPORT
          - HMPA_EVENT_TYPE
          - HMPA_PROCESS_VERSION
          - HMPA_PROCESS_PID
          - HMPA_PROCESS_PATH
          - HOME_FAMILY_ID
          - HOME_SCAN_LABEL
          - HOME_SCAN_STATE
          - HOME_SCAN_CLEAN
          - HOME_SCAN_REBOOT
          - HOME_COOKIES_COUNT
          - HOME_COOKIES_DOMAINS
          - HOME_REMNANT_FAMILY
          - HOME_REMNANT_NAME
          - HOME_REMNANT_PATHS
          type: string
      type: object
    EventAggregate:
      description: Sophos Central Event Model
      example:
        next_cursor: next_cursor
        has_more: true
        items:
        - severity: NONE
          core_remedy_items:
            totalItems: 0
            items:
            - result: NOT_APPLICABLE
              descriptor: descriptor
              type: type
            - result: NOT_APPLICABLE
              descriptor: descriptor
              type: type
          appCerts:
          - thumbprint: thumbprint
            signer: signer
          - thumbprint: thumbprint
            signer: signer
          origin: origin
          created_at: created_at
          endpoint_id: endpoint_id
          source: source
          type: type
          when: when
          endpoint_type: endpoint_type
          user_id: user_id
          whitelist_properties:
          - property: property
            type: SHA_256
          - property: property
            type: SHA_256
          name: name
          details:
          - property: property
            type: CORE_EVENT_REQUEST_ID
          - property: property
            type: CORE_EVENT_REQUEST_ID
          location: location
          id: id
          threat: threat
          appSha256: appSha256
          customer_id: customer_id
          source_info:
            key: source_info
          group: group
        - severity: NONE
          core_remedy_items:
            totalItems: 0
            items:
            - result: NOT_APPLICABLE
              descriptor: descriptor
              type: type
            - result: NOT_APPLICABLE
              descriptor: descriptor
              type: type
          appCerts:
          - thumbprint: thumbprint
            signer: signer
          - thumbprint: thumbprint
            signer: signer
          origin: origin
          created_at: created_at
          endpoint_id: endpoint_id
          source: source
          type: type
          when: when
          endpoint_type: endpoint_type
          user_id: user_id
          whitelist_properties:
          - property: property
            type: SHA_256
          - property: property
            type: SHA_256
          name: name
          details:
          - property: property
            type: CORE_EVENT_REQUEST_ID
          - property: property
            type: CORE_EVENT_REQUEST_ID
          location: location
          id: id
          threat: threat
          appSha256: appSha256
          customer_id: customer_id
          source_info:
            key: source_info
          group: group
      properties:
        has_more:
          type: boolean
        items:
          items:
            $ref: '#/components/schemas/LegacyEventEntity'
          type: array
        next_cursor:
          description: Value of the next cursor. This will be used to make next call
            of api
          type: string
      type: object
    AlertEntity:
      description: This model wraps up an Alert. This contains various fields that
        contain information regarding the alert that was generated.
      example:
        severity: LOW
        data:
          key: '{}'
        created_at: created_at
        description: description
        source: source
        type: type
        when: when
        threat_cleanable: true
        event_service_event_id: event_service_event_id
        location: location
        id: id
        threat: threat
        customer_id: customer_id
        info:
          key: '{}'
      properties:
        created_at:
          description: The date at which the alert was created
          type: string
        customer_id:
          description: The unique identifier of the customer linked with this record
          type: string
        data:
          additionalProperties:
            type: object
          type: object
        description:
          description: The description of the alert that was generated
          type: string
        event_service_event_id:
          description: The Event Services event id
          type: string
        id:
          description: Identifier for the alert
          type: string
        info:
          additionalProperties:
            type: object
          type: object
        location:
          description: The location captured for this record
          type: string
        severity:
          description: The severity for this alert
          enum:
          - LOW
          - MEDIUM
          - HIGH
          type: string
        source:
          description: Describes the source from alert was generated
          type: string
        threat:
          description: The name of the threat responsible for the generation of alert
          type: string
        threat_cleanable:
          type: boolean
        type:
          description: Describes the type of the device on which alert was generated
          type: string
        when:
          description: The date at which the alert was created
          type: string
      type: object
    TamperProtectionEntity:
      example:
        globally_enabled: true
        password: password
        previous_passwords:
        - password: password
          invalidated:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
        - password: password
          invalidated:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
        enabled: true
      properties:
        enabled:
          type: boolean
        globally_enabled:
          type: boolean
        password:
          type: string
        previous_passwords:
          items:
            $ref: '#/components/schemas/PreviousPasswordEntity'
          type: array
      type: object
    Chronology:
      example:
        zone:
          fixed: true
          id: id
      properties:
        zone:
          $ref: '#/components/schemas/DateTimeZone'
      type: object
    InstallerInfoResponse:
      description: Sophos Central Installer Info Model
      example:
        installerInfo:
        - beta: true
          command: command
          platform: platform
          productName: productName
          url: url
        - beta: true
          command: command
          platform: platform
          productName: productName
          url: url
      properties:
        installerInfo:
          items:
            $ref: '#/components/schemas/InstallerInfo'
          type: array
      type: object
    PreviousPasswordEntity:
      example:
        password: password
        invalidated:
          dayOfYear: 7
          equalNow: true
          year: 5
          weekyear: 4
          chronology:
            zone:
              fixed: true
              id: id
          weekOfWeekyear: 1
          secondOfMinute: 7
          millisOfDay: 4
          monthOfYear: 1
          beforeNow: true
          dayOfWeek: 2
          minuteOfDay: 1
          dayOfMonth: 5
          era: 9
          zone:
            fixed: true
            id: id
          yearOfCentury: 9
          centuryOfEra: 5
          hourOfDay: 3
          secondOfDay: 6
          millis: 2
          yearOfEra: 9
          minuteOfHour: 1
          afterNow: true
          millisOfSecond: 7
      properties:
        invalidated:
          $ref: '#/components/schemas/DateTime'
        password:
          type: string
      type: object
    CoreRemedyItems:
      example:
        totalItems: 0
        items:
        - result: NOT_APPLICABLE
          descriptor: descriptor
          type: type
        - result: NOT_APPLICABLE
          descriptor: descriptor
          type: type
      properties:
        items:
          items:
            $ref: '#/components/schemas/CoreRemedyItem'
          type: array
        totalItems:
          format: int32
          type: integer
      type: object
    CustomerLicense:
      example:
        expired: true
        license_id: license_id
        license_type: ALPHA
        expires_on:
          dayOfYear: 7
          equalNow: true
          year: 5
          weekyear: 4
          chronology:
            zone:
              fixed: true
              id: id
          weekOfWeekyear: 1
          secondOfMinute: 7
          millisOfDay: 4
          monthOfYear: 1
          beforeNow: true
          dayOfWeek: 2
          minuteOfDay: 1
          dayOfMonth: 5
          era: 9
          zone:
            fixed: true
            id: id
          yearOfCentury: 9
          centuryOfEra: 5
          hourOfDay: 3
          secondOfDay: 6
          millis: 2
          yearOfEra: 9
          minuteOfHour: 1
          afterNow: true
          millisOfSecond: 7
        quota: 7
        id:
          date: 2000-01-23T04:56:07.000+00:00
          machineIdentifier: 6
          counter: 0
          processIdentifier: 1
          time: 5
          timeSecond: 5
          timestamp: 2
        license_code: license_code
        starts_on:
          dayOfYear: 7
          equalNow: true
          year: 5
          weekyear: 4
          chronology:
            zone:
              fixed: true
              id: id
          weekOfWeekyear: 1
          secondOfMinute: 7
          millisOfDay: 4
          monthOfYear: 1
          beforeNow: true
          dayOfWeek: 2
          minuteOfDay: 1
          dayOfMonth: 5
          era: 9
          zone:
            fixed: true
            id: id
          yearOfCentury: 9
          centuryOfEra: 5
          hourOfDay: 3
          secondOfDay: 6
          millis: 2
          yearOfEra: 9
          minuteOfHour: 1
          afterNow: true
          millisOfSecond: 7
        suspended: true
      properties:
        expired:
          type: boolean
        expires_on:
          $ref: '#/components/schemas/DateTime'
        id:
          $ref: '#/components/schemas/ObjectId'
        license_code:
          type: string
        license_id:
          type: string
        license_type:
          enum:
          - ALPHA
          - BETA
          - EAP
          - ENTERPRISE
          - FULL
          - FREE
          - MONTHLY
          - MSP
          - TERMED
          - TRIAL
          - VIRTUAL
          type: string
        quota:
          format: int32
          type: integer
        starts_on:
          $ref: '#/components/schemas/DateTime'
        suspended:
          type: boolean
      type: object
    ObjectId:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        machineIdentifier: 6
        counter: 0
        processIdentifier: 1
        time: 5
        timeSecond: 5
        timestamp: 2
      properties:
        counter:
          format: int32
          type: integer
        date:
          format: date-time
          type: string
        machineIdentifier:
          format: int32
          type: integer
        processIdentifier:
          format: int32
          type: integer
        time:
          format: int64
          type: integer
        timeSecond:
          format: int32
          type: integer
        timestamp:
          format: int32
          type: integer
      type: object
    EndpointAdSyncInfo:
      example:
        name: name
        dn: dn
        external_id: external_id
        from_ad_sync: true
      properties:
        dn:
          type: string
        external_id:
          type: string
        from_ad_sync:
          type: boolean
        name:
          type: string
      type: object
    CurrentLicensesResponse:
      description: Sophos Central License Model
      example:
        licenses:
        - expired: true
          license_id: license_id
          license_type: ALPHA
          expires_on:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
          quota: 7
          id:
            date: 2000-01-23T04:56:07.000+00:00
            machineIdentifier: 6
            counter: 0
            processIdentifier: 1
            time: 5
            timeSecond: 5
            timestamp: 2
          license_code: license_code
          starts_on:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
          suspended: true
        - expired: true
          license_id: license_id
          license_type: ALPHA
          expires_on:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
          quota: 7
          id:
            date: 2000-01-23T04:56:07.000+00:00
            machineIdentifier: 6
            counter: 0
            processIdentifier: 1
            time: 5
            timeSecond: 5
            timestamp: 2
          license_code: license_code
          starts_on:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
          suspended: true
      properties:
        licenses:
          items:
            $ref: '#/components/schemas/CustomerLicense'
          type: array
      type: object
    EndpointWhitelistProperties:
      example:
        property: property
        type: SHA_256
      properties:
        property:
          type: string
        type:
          enum:
          - SHA_256
          - CERTIFICATE_SIGNER
          - PATH
          - THUMBPRINT
          - PROCESS_NAME
          type: string
      type: object
    CustomerFeature:
      example:
        valid: true
        expired: true
        featureCode: f_invalid
        generatedFromLicenseId: generatedFromLicenseId
        expiresOn:
          dayOfYear: 7
          equalNow: true
          year: 5
          weekyear: 4
          chronology:
            zone:
              fixed: true
              id: id
          weekOfWeekyear: 1
          secondOfMinute: 7
          millisOfDay: 4
          monthOfYear: 1
          beforeNow: true
          dayOfWeek: 2
          minuteOfDay: 1
          dayOfMonth: 5
          era: 9
          zone:
            fixed: true
            id: id
          yearOfCentury: 9
          centuryOfEra: 5
          hourOfDay: 3
          secondOfDay: 6
          millis: 2
          yearOfEra: 9
          minuteOfHour: 1
          afterNow: true
          millisOfSecond: 7
        protection: true
        expirationProcessed: true
        licenseCode: licenseCode
      properties:
        expirationProcessed:
          type: boolean
        expired:
          type: boolean
        expiresOn:
          $ref: '#/components/schemas/DateTime'
        featureCode:
          enum:
          - f_invalid
          - f_srv
          - f_srv_av
          - f_srv_appctl
          - f_srv_devctl
          - f_srv_devctl_block
          - f_srv_dlp
          - f_srv_lockdown
          - f_srv_web
          - f_srv_mtd
          - f_srv_xpd
          - f_srv_hbt
          - f_srv_stac
          - f_srv_ml
          - f_srv_efw
          - f_srv_extsup_win2k3
          - f_srv_fim
          - f_srv_edr
          - f_srv_mdr
          - f_srv_blocklisting
          - f_srv_isolation
          - f_srv_file_submission_l2
          - f_srv_file_submission_l3
          - f_srv_on_demand_rca
          - f_srv_forensic_snapshot
          - f_virt_ep_av
          - f_virt_srv_av
          - f_ep
          - f_ep_appctl
          - f_ep_devctl
          - f_ep_dlp
          - f_ep_av
          - f_ep_web
          - f_ep_efw
          - f_ep_denc_deprecated
          - f_ep_denc
          - f_ep_fenc
          - f_ep_xpd
          - f_ep_stac
          - f_ep_ntp
          - f_ep_ntp_adv
          - f_ep_ntp_xg
          - f_ep_hbt
          - f_ep_hbt_adv
          - f_ep_hbt_xg
          - f_ep_extsup_winxp
          - f_ep_ml
          - f_ep_edr
          - f_ep_mdr
          - f_ep_blocklisting
          - f_ep_isolation
          - f_ep_file_submission_l2
          - f_ep_file_submission_l3
          - f_ep_on_demand_rca
          - f_ep_forensic_snapshot
          - f_mob
          - f_mob_lock
          - f_mob_locate
          - f_mob_wipe
          - f_mob_policy_compliance
          - f_mob_policy_exchange
          - f_mob_policy_passcode
          - f_mob_policy_restrictions
          - f_mob_policy_vpn
          - f_mob_policy_wifi
          - f_mob_container_email
          - f_mob_container_mcm
          - f_mob_container_docs
          - f_mob_container_browser
          - f_smc_migration
          - f_smsec
          - f_smsec_webfiltering
          - f_csg
          - f_multi_policies
          - f_support
          - f_user_specific
          - f_ad_sync
          - f_xgemail
          - f_xgemail_antispam
          - f_xgemail_av
          - f_xgemail_eminbox
          - f_xgemail_quarantine
          - f_xgemail_ssp
          - f_xgemail_ad_sync
          - f_xgemail_dkim
          - f_xgemail_spf
          - f_xgemail_anti_phish
          - f_xgemail_att_policy
          - f_xgemail_dmarc
          - f_xgemail_toc_url_protect
          - f_xgemail_sandbox
          - f_xgemail_content_filter
          - f_xgemail_content_filter_v2
          - f_xgemail_user_policy
          - f_xgemail_encryption
          - f_xgemail_smart_banner
          - f_wifi_entry_standard
          - f_wifi_performance_standard
          - f_central_wifi_standard
          - f_phish_training
          type: string
        generatedFromLicenseId:
          type: string
        licenseCode:
          type: string
        protection:
          type: boolean
        valid:
          type: boolean
      type: object
    DateTimeZone:
      example:
        fixed: true
        id: id
      properties:
        fixed:
          type: boolean
        id:
          type: string
      type: object
    CoreRemedyItem:
      example:
        result: NOT_APPLICABLE
        descriptor: descriptor
        type: type
      properties:
        descriptor:
          type: string
        result:
          enum:
          - NOT_APPLICABLE
          - SUCCESS
          - NOT_FOUND
          - DELETED
          - FAILED_TO_DELETE
          - WHITELISTED
          - OTHER_ERROR
          - FAILED_TO_DELETE_SYSTEM_PROTECTED
          type: string
        type:
          type: string
      type: object
    InstallerInfo:
      example:
        beta: true
        command: command
        platform: platform
        productName: productName
        url: url
      properties:
        beta:
          type: boolean
        command:
          type: string
        platform:
          type: string
        productName:
          type: string
        url:
          type: string
      type: object
    CustomerFeaturesResponse:
      description: Sophos Central Customer Feature Model
      example:
        features:
        - valid: true
          expired: true
          featureCode: f_invalid
          generatedFromLicenseId: generatedFromLicenseId
          expiresOn:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
          protection: true
          expirationProcessed: true
          licenseCode: licenseCode
        - valid: true
          expired: true
          featureCode: f_invalid
          generatedFromLicenseId: generatedFromLicenseId
          expiresOn:
            dayOfYear: 7
            equalNow: true
            year: 5
            weekyear: 4
            chronology:
              zone:
                fixed: true
                id: id
            weekOfWeekyear: 1
            secondOfMinute: 7
            millisOfDay: 4
            monthOfYear: 1
            beforeNow: true
            dayOfWeek: 2
            minuteOfDay: 1
            dayOfMonth: 5
            era: 9
            zone:
              fixed: true
              id: id
            yearOfCentury: 9
            centuryOfEra: 5
            hourOfDay: 3
            secondOfDay: 6
            millis: 2
            yearOfEra: 9
            minuteOfHour: 1
            afterNow: true
            millisOfSecond: 7
          protection: true
          expirationProcessed: true
          licenseCode: licenseCode
      properties:
        features:
          items:
            $ref: '#/components/schemas/CustomerFeature'
          type: array
      type: object
    LegacyEventEntity:
      description: This model wraps up an Event. This contains various fields that
        contain information regarding the event that was generated.
      example:
        severity: NONE
        core_remedy_items:
          totalItems: 0
          items:
          - result: NOT_APPLICABLE
            descriptor: descriptor
            type: type
          - result: NOT_APPLICABLE
            descriptor: descriptor
            type: type
        appCerts:
        - thumbprint: thumbprint
          signer: signer
        - thumbprint: thumbprint
          signer: signer
        origin: origin
        created_at: created_at
        endpoint_id: endpoint_id
        source: source
        type: type
        when: when
        endpoint_type: endpoint_type
        user_id: user_id
        whitelist_properties:
        - property: property
          type: SHA_256
        - property: property
          type: SHA_256
        name: name
        details:
        - property: property
          type: CORE_EVENT_REQUEST_ID
        - property: property
          type: CORE_EVENT_REQUEST_ID
        location: location
        id: id
        threat: threat
        appSha256: appSha256
        customer_id: customer_id
        source_info:
          key: source_info
        group: group
      properties:
        appCerts:
          description: Certificate info of the application associated with the threat,
            if available
          items:
            $ref: '#/components/schemas/EndpointCoreEventCertificate'
          type: array
        appSha256:
          description: SHA 256 hash of the application associated with the threat,
            if available
          type: string
        core_remedy_items:
          $ref: '#/components/schemas/CoreRemedyItems'
        created_at:
          description: The date at which the event was created
          type: string
        customer_id:
          description: The identifier of the customer for which record is created
          type: string
        details:
          items:
            $ref: '#/components/schemas/EventDetailProperty'
          type: array
        endpoint_id:
          description: The corresponding endpoint id associated with the record
          type: string
        endpoint_type:
          description: The corresponding endpoint type associated with the record
          type: string
        group:
          description: The group associated with the group
          type: string
        id:
          description: The Identifier for the event
          type: string
        location:
          description: The location captured for this record
          type: string
        name:
          description: The name of the record created
          type: string
        origin:
          description: originating component of a detection
          type: string
        severity:
          description: The severity for this alert
          enum:
          - NONE
          - LOW
          - MEDIUM
          - HIGH
          - CRITICAL
          type: string
        source:
          description: The source for this record
          type: string
        source_info:
          additionalProperties:
            type: string
          description: Detailed source information for this record
          type: object
        threat:
          description: The threat associated with the record
          type: string
        type:
          description: The type of this record
          type: string
        user_id:
          description: The identifier of the user for which record is created
          type: string
        when:
          description: The date at which the event was created
          type: string
        whitelist_properties:
          items:
            $ref: '#/components/schemas/EndpointWhitelistProperties'
          type: array
      type: object
    HashesResponse:
      description: Sophos Central Hashes Model
      example:
        hashes: '{}'
      properties:
        hashes:
          type: object
      type: object
    EndpointEntity:
      example:
        adSyncInfo:
          name: name
          dn: dn
          external_id: external_id
          from_ad_sync: true
        device_encryption_status_unmanaged: true
        feature_codes:
        - feature_codes
        - feature_codes
        last_user_id: last_user_id
        awsInfo:
          key: awsInfo
        last_activity: last_activity
        last_user: last_user
        group_full_name: group_full_name
        health_status: 1
        id: id
        beta: true
        java_id: java_id
        license_codes:
        - license_codes
        - license_codes
        info: '{}'
        heartbeat_utm_name: heartbeat_utm_name
        early_access_program: early_access_program
        decloned_from: decloned_from
        registered_at: registered_at
        group_name: group_name
        machine_id: machine_id
        tamper_protection:
          globally_enabled: true
          password: password
          previous_passwords:
          - password: password
            invalidated:
              dayOfYear: 7
              equalNow: true
              year: 5
              weekyear: 4
              chronology:
                zone:
                  fixed: true
                  id: id
              weekOfWeekyear: 1
              secondOfMinute: 7
              millisOfDay: 4
              monthOfYear: 1
              beforeNow: true
              dayOfWeek: 2
              minuteOfDay: 1
              dayOfMonth: 5
              era: 9
              zone:
                fixed: true
                id: id
              yearOfCentury: 9
              centuryOfEra: 5
              hourOfDay: 3
              secondOfDay: 6
              millis: 2
              yearOfEra: 9
              minuteOfHour: 1
              afterNow: true
              millisOfSecond: 7
          - password: password
            invalidated:
              dayOfYear: 7
              equalNow: true
              year: 5
              weekyear: 4
              chronology:
                zone:
                  fixed: true
                  id: id
              weekOfWeekyear: 1
              secondOfMinute: 7
              millisOfDay: 4
              monthOfYear: 1
              beforeNow: true
              dayOfWeek: 2
              minuteOfDay: 1
              dayOfMonth: 5
              era: 9
              zone:
                fixed: true
                id: id
              yearOfCentury: 9
              centuryOfEra: 5
              hourOfDay: 3
              secondOfDay: 6
              millis: 2
              yearOfEra: 9
              minuteOfHour: 1
              afterNow: true
              millisOfSecond: 7
          enabled: true
        transport: transport
        azureInfo:
          key: azureInfo
        deleted_at: deleted_at
        alert_status: 6
        is_adsync_group: true
        cloned: true
        endpoint_type: endpoint_type
        group_id: group_id
        name: name
        assignedProducts:
        - assignedProducts
        - assignedProducts
        is_caching_proxy: true
        status: '{}'
      properties:
        adSyncInfo:
          $ref: '#/components/schemas/EndpointAdSyncInfo'
        alert_status:
          format: int32
          type: integer
        assignedProducts:
          items:
            type: string
          type: array
        awsInfo:
          additionalProperties:
            type: string
          type: object
        azureInfo:
          additionalProperties:
            type: string
          type: object
        beta:
          type: boolean
        cloned:
          type: boolean
        decloned_from:
          type: string
        deleted_at:
          type: string
        device_encryption_status_unmanaged:
          type: boolean
        early_access_program:
          type: string
        endpoint_type:
          type: string
        feature_codes:
          items:
            type: string
          type: array
        group_full_name:
          type: string
        group_id:
          type: string
        group_name:
          type: string
        health_status:
          format: int32
          type: integer
        heartbeat_utm_name:
          type: string
        id:
          type: string
        info:
          type: object
        is_adsync_group:
          type: boolean
        is_caching_proxy:
          type: boolean
        java_id:
          type: string
        last_activity:
          type: string
        last_user:
          type: string
        last_user_id:
          type: string
        license_codes:
          items:
            type: string
          type: array
        machine_id:
          type: string
        name:
          type: string
        registered_at:
          type: string
        status:
          type: object
        tamper_protection:
          $ref: '#/components/schemas/TamperProtectionEntity'
        transport:
          type: string
      type: object
  securitySchemes:
    api_key:
      in: header
      name: x-api-key
      type: apiKey
